AWSTemplateFormatVersion: "2010-09-09"
Description: Top-level ECS stack

Parameters:
  DomainName:
    Type: String
    Description: Domain for the load balancer
  ClientDomain:
    Type: String
    Description: Domain of the client app for CORS settings


Resources:

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load-balancer.yml
      Parameters:
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportPublicSubnets
        DomainName: !Ref

  SupportService:
    Type: AWS::CloudFormation::Stack
    DependsOn: [LoadBalancer, Cluster]
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Cluster: !Ref Cluster
        LoadBalancer: !GetAtt LoadBalancer.Outputs.LoadBalancer
        LoadBalancerListener: !GetAtt LoadBalancer.Outputs.Listener
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportPublicSubnets
        Repository: !ImportValue SupportSupportServiceRepo
        Name: support-service
        ExportName: SupportSupportService
        PathPattern: "/support/*"
        HealthCheckPath: "/support/"
        ClientDomain: !Ref ClientDomain

Outputs:
  ServiceUrl:
    Description: The load balancer URL
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl
