AWSTemplateFormatVersion: "2010-09-09"
Description: Todo

Resources:

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load-balancer.yml
      Parameters:
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cluster.yml
      Parameters:
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !ImportValue SupportSubnets
        Repository: !ImportValue SupportUserServiceRepo

Outputs:
  ServiceUrl:
    Description: The sample service that is being continuously deployed.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl
