AWSTemplateFormatVersion: "2010-09-09"
Description: Top-level ECS stack

Resources:

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load-balancer.yml
      Parameters:
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cluster.yml
      Parameters:
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets

  UserService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        TargetGroup: !GetAtt LoadBalancer.Outputs.UserServiceTargetGroup
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets
        Repository: !ImportValue SupportUserServiceRepo
        Name: user-service
        ExportName: SupportUserService

  SupportService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./service.yml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        TargetGroup: !GetAtt LoadBalancer.Outputs.SupportServiceTargetGroup
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        VpcId: !ImportValue SupportVPC
        Subnets: !ImportValue SupportSubnets
        Repository: !ImportValue SupportSupportServiceRepo
        Name: support-service
        ExportName: SupportSupportService

Outputs:
  ServiceUrl:
    Description: The load balancer URL
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl
