---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Type: String


Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-alb
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
      VpcId: !Ref VpcId

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP # TODO HTTPS https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref UserServiceTargetGroup

  UserServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP # TODO HTTPS
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /user
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  UserServiceListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /user
      Actions:
        - TargetGroupArn: !Ref UserServiceTargetGroup
          Type: forward

  SupportServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP # TODO HTTPS
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /support
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  SupportServiceListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - /support
      Actions:
        - TargetGroupArn: !Ref SupportServiceTargetGroup
          Type: forward


Outputs:
  UserServiceTargetGroup:
    Value: !Ref UserServiceTargetGroup
  SupportServiceTargetGroup:
    Value: !Ref SupportServiceTargetGroup
  ServiceUrl:
    Description: URL of the load balancer for the sample service.
    Value: !Sub http://${LoadBalancer.DNSName}
  SecurityGroup:
    Value: !Ref SecurityGroup
