AWSTemplateFormatVersion: "2010-09-09"
Description: Top-level pipeline stack
Parameters:
  GitHubUser:
    Type: String
    Description: Your username on GitHub.
  GitHubRepo:
    Type: String
    Description: The repo name of the sample service.
  GitHubBranch:
    Type: String
    Description: The branch of the repo to continuously deploy.
  GitHubToken:
    Type: String
    Description: Token for the user specified above. (https://github.com/settings/tokens)

Resources:

  UserServicePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./pipeline.yml
      Parameters:
        Name: user-service
        Cluster: !ImportValue SupportCluster
        Service: !ImportValue SupportUserService
        Repository: !ImportValue SupportUserServiceRepo
        BuildSpecPath: user-service/buildspec.yml
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

  SupportServicePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./pipeline.yml
      Parameters:
        Name: support-service
        Cluster: !ImportValue SupportCluster
        Service: !ImportValue SupportSupportService
        Repository: !ImportValue SupportSupportServiceRepo
        BuildSpecPath: support-service/buildspec.yml
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
